filters:
    publish_pointclouds_only_if_there_is_subscribers: false
    reference_pointcloud:
        1_voxel_grid:
            leaf_size_x: 0.002
            leaf_size_y: 0.002
            leaf_size_z: 0.002
            filter_limit_field_name: 'z'
            filter_limit_min: -5.0
            filter_limit_max: 5.0
            downsample_all_data: true
            save_leaf_layout: false
    ambient_pointcloud_feature_registration:
#        0_hsv_segmentation: # PhotoNeo grayscale image -> can only segment using the HSV value channel
#            minimum_hue: 0.0
#            maximum_hue: 360.0
#            minimum_saturation: 0.0
#            maximum_saturation: 1.0
#            minimum_value: 0.1
#            maximum_value: 1.0
#            invert_segmentation: false
#            filtered_cloud_publish_topic: 'filtered_pointcloud_hsv_segmentation'
        1_crop_box:
            box_min_x: 0.75
            box_min_y: -.5
            box_min_z: 0.0
            box_max_x: 1.75
            box_max_y: .5
            box_max_z: .5
            invert_selection: true
            filtered_cloud_publish_topic: 'filtered_pointcloud_cropbox'
        2_voxel_grid:
            leaf_size_x: 0.004
            leaf_size_y: 0.004
            leaf_size_z: 0.004
            filter_limit_field_name: 'z'
            filter_limit_min: -5.0
            filter_limit_max: 5.0
            downsample_all_data: true
            save_leaf_layout: false
            filtered_cloud_publish_topic: 'filtered_pointcloud_voxel_grid'
