filters:
    publish_pointclouds_only_if_there_is_subscribers: false
    reference_pointcloud:
    #     1_voxel_grid:
    #         leaf_size_x: 0.002
    #         leaf_size_y: 0.002
    #         leaf_size_z: 0.002
    #         filter_limit_field_name: 'z'
    #         filter_limit_min: -5.0
    #         filter_limit_max: 5.0
    #         downsample_all_data: true
    #         save_leaf_layout: false
    #         filtered_cloud_publish_topic: ''
        2_random_sample:
            number_of_random_samples: 6000
            invert_sampling: false
            filtered_cloud_publish_topic: ''
    ambient_pointcloud_feature_registration:
        #0_crop_box:
        #    box_min_x: -1.4
        #    box_min_y: -1.4
        #    box_min_z: -1.4
        #    box_max_x: 1.4
        #    box_max_y: 1.4
        #    box_max_z: 1.4
      #      invert_selection: false
        #    filtered_cloud_publish_topic: 'filtered_pointcloud_cropbox'
        # 1_voxel_grid:
        #     leaf_size_x: 0.0025
        #     leaf_size_y: 0.0025
        #     leaf_size_z: 0.0025
        #     filter_limit_field_name: 'z'
        #     filter_limit_min: -5.0
        #     filter_limit_max: 5.0
        #     downsample_all_data: true
        #     save_leaf_layout: false
        #     filtered_cloud_publish_topic: 'filtered_pointcloud_voxel_grid'
        2_random_sample:
            number_of_random_samples: 6000
            invert_sampling: false
            filtered_cloud_publish_topic: 'filtered_pointcloud_random_sample_1'
        3_radius_outlier_removal:
            radius_search: 0.007
            min_neighbors_in_radius: 15
            invert_removal: false
            filtered_cloud_publish_topic: 'filtered_pointcloud_radius_outlier_removal_1'
        # 4_statistical_outlier_removal:
        #     number_of_neighbors_for_mean_distance_estimation: 27
        #     standard_deviation_multiplier: 7.0
        #     invert_selection: false
        #     filtered_cloud_publish_topic: 'filtered_pointcloud_statistical_outlier_removal_1'
    ambient_pointcloud_filters_after_normal_estimation:
        #1_plane_segmentation:
        #    sample_consensus_method: "SAC_RANSAC"                   # SAC_RANSAC | SAC_LMEDS | SAC_MSAC | SAC_RRANSAC | SAC_RMSAC | SAC_MLESAC | SAC_PROSAC
        #    use_surface_normals: true
        #    sample_consensus_maximum_distance_of_sample_to_plane: 0.005
        #    sample_consensus_normals_difference_weight: 0.07
        #    sample_consensus_number_of_iterations: 1000
        #    sample_consensus_probability_of_sample_not_be_an_outlier: 0.2
        #    plane_convex_hull_scaling_factor: 3.0
        #    segmentation_minimum_distance_to_plane: 0.006
        #    segmentation_maximum_distance_to_plane: 0.2
        #    plane_inliers_cloud_publish_topic: 'filtered_pointcloud_plane_segmentation_inliers'
        #    plane_inliers_convex_hull_cloud_publish_topic: 'filtered_pointcloud_plane_segmentation_inliers_convex_hull'
        #    filtered_cloud_publish_topic: 'filtered_pointcloud_plane_segmentation'
        2_random_sample:
            number_of_random_samples: 6000
            invert_sampling: false
            filtered_cloud_publish_topic: 'filtered_pointcloud_random_sample_2'
        6_radius_outlier_removal:
            radius_search: 0.007
            min_neighbors_in_radius: 10
            invert_removal: false
            filtered_cloud_publish_topic: 'filtered_pointcloud_radius_outlier_removal_2'
        # 7_statistical_outlier_removal:
        #     number_of_neighbors_for_mean_distance_estimation: 20
        #     standard_deviation_multiplier: 3.7
        #     invert_selection: false
        #     filtered_cloud_publish_topic: 'filtered_pointcloud_statistical_outlier_removal_2'
        8_random_sample:
            number_of_random_samples: 6000
            invert_sampling: false
            filtered_cloud_publish_topic: 'filtered_pointcloud_random_sample_3'
