filters:
    ambient_pointcloud_filters_after_normal_estimation:
#        0_plane_segmentation:
#            use_surface_normals: true
#            sample_consensus_maximum_distance_of_sample_to_plane: 0.01
#            sample_consensus_normals_difference_weight: 0.1
#            sample_consensus_number_of_iterations: 1000
#            sample_consensus_probability_of_sample_not_be_an_outlier: 0.5
#            plane_convex_hull_scaling_factor: 1.0
#            segmentation_minimum_distance_to_plane: 0.05
#            segmentation_maximum_distance_to_plane: 0.45
#            plane_inliers_cloud_publish_topic: 'plane_inliers'
#            plane_inliers_cloud_publish_topic_frame_id: ''
#            plane_inliers_convex_hull_cloud_publish_topic: 'plane_inliers_convex_hull'
#            plane_inliers_convex_hull_cloud_publish_topic_frame_id: ''
#            filtered_cloud_publish_topic: 'plane_removal_filtereed_pointcloud_clusters_colored'
#            filtered_cloud_publish_topic_frame_id: ''
        1_euclidean_clustering:
            cluster_tolerance: 0.01
            min_cluster_size: 100
            min_cluster_index: 0
            max_cluster_index: 1
            filtered_cloud_publish_topic: 'filtered_pointcloud_clustering'
            cluster_selector:
                sorting_algorithm: "MaxClusterSizeSorter" # Available sorters: [ MinClusterSizeSorter | MaxClusterSizeSorter | MinDistanceToOriginSorter | MaxDistanceToOriginSorter | MinAxisValueSorter | MaxAxisValueSorter ]
                sorting_axis: "Z" # Available axis: [ X | Y | Z ] -> only used with [ MinAxisValueSorter | MaxAxisValueSorter ]
                clusters_colored_cloud_publish_topic: 'filtered_pointcloud_clusters_colored'
